### ISSUE TITLE
Quarto Conditional Content directives appearing in output when using quarto and gt

### ISSUE THREAD

**Issue by donert** [rstudio/gt#1430]
## Description

I am trying to create a document which rotates a gt() generated table into landscape when rendered as a pdf. Using conditional content works but I am getting 'garbage' in the output. For example when rendering as html I see a spurious back tick at the beginning and `{=html} at the end. The pdf render is clean. Attached is the code to reproduce. This stack overflow  question includes an image of the erroneous result. https://stackoverflow.com/questions/77024090/conditional-content-directives-appearing-in-output-when-using-quarto-and-gt

## Reproducible example

```
---
title: "conditional test"
format:
  html:
     abstract: "Demonstrates spurious output for html"
  pdf:
    abstract: "pdf output is clean"
    number-sections: true 
    toc: true
    toc-depth: 2
    header-includes:
       - \usepackage{rotating}    
---

```{r echo=FALSE}
library(gt) 

table <- data.frame(col1=letters, col2=LETTERS) |> head(3)  |> gt() 
#table <- "Simple text which renders cleanly."
```

:::{.content-visible when-format="pdf"}
`r sprintf("\\begin{sidewaysfigure}")`
`r table` pdf
`r sprintf("\\end{sidewaysfigure}")`
:::

:::{.content-visible when-format="html"}
`r table` html
:::
```

## Expected result

I expect the output to not include those fragments of the conditional content statement. 
Because this works properly with simple text output I suspect that gt is adding delimiters that are incorrect.

## Session info

R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.5.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/Toronto
tzcode source: internal

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] DiagrammeRsvg_0.1 rsvg_2.4.0        gt_0.9.0          here_1.0.1        lubridate_1.9.2   forcats_1.0.0     stringr_1.5.0    
 [8] dplyr_1.1.2       purrr_1.0.1       tidyr_1.3.0       tibble_3.2.1      tidyverse_2.0.0   DiagrammeR_1.0.10 formattable_0.2.1
[15] glue_1.6.2        kableExtra_1.3.4  ggplot2_3.4.2     jpeg_0.1-10       knitr_1.43        readxl_1.4.3      readr_2.1.4      

loaded via a namespace (and not attached):
 [1] gtable_0.3.3       xfun_0.39          htmlwidgets_1.6.2  visNetwork_2.1.2   lattice_0.21-8     tzdb_0.4.0         vctrs_0.6.3       
 [8] tools_4.3.1        generics_0.1.3     curl_5.0.1         fansi_1.0.4        highr_0.10         pkgconfig_2.0.3    Matrix_1.5-4.1    
[15] RColorBrewer_1.1-3 webshot_0.5.5      lifecycle_1.0.3    compiler_4.3.1     farver_2.1.1       munsell_0.5.0      htmltools_0.5.5   
[22] sass_0.4.6         yaml_2.3.7         crayon_1.5.2       pillar_1.9.0       ellipsis_0.3.2     rsconnect_1.0.1    nlme_3.1-162      
[29] tidyselect_1.2.0   rvest_1.0.3        digest_0.6.31      stringi_1.7.12     splines_4.3.1      labeling_0.4.2     rprojroot_2.0.3   
[36] fastmap_1.1.1      colorspace_2.1-0   cli_3.6.1          magrittr_2.0.3     utf8_1.2.3         clipr_0.8.0        withr_2.5.0       
[43] scales_1.2.1       timechange_0.2.0   rmarkdown_2.22     httr_1.4.6         cellranger_1.1.0   hms_1.1.3          evaluate_0.21     
[50] V8_4.3.0           viridisLite_0.4.2  mgcv_1.8-42        rlang_1.1.1        Rcpp_1.0.10        xml2_1.3.4         svglite_2.1.1     
[57] rstudioapi_0.14    jsonlite_1.8.5     R6_2.5.1           systemfonts_1.0.4
