### ISSUE TITLE
Feature: Hide specified columns below specific screen widths

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#189]
This would allow us to specify which column(s) would be displayed at or above a specified width. For each width, this would require a CSS rule that would be something like this:

```css
@media only screen and (max-width: [width]px) {
  .gt_hide_col_[width] {
    display: none;
  }
}
```

The class would need to be applied to each of the `<th>` and `<td>` tags for the columns to be hidden below the `width`.

Thanks @jcheng5 for suggesting this feature.
