### ISSUE TITLE
Top lines in cell borders are overridden by row lines

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#358]
In a gt table rendered as HTML, the top line of a cell border (created using `tab_style()` -> `cell_borders()`) is not visible unless it is `2px` or larger. The table body row lines currently have a width of `"thin"`, which is `1px`.

Here is a reproducible example with screenshot, where `cell_borders()` without any arguments draws a `1px` box at each location:

```r
library(gt)
library(tidyverse)

exibble %>%
  select(num, date, datetime) %>%
  gt() %>%
  tab_style(
    style = cell_borders(),
    locations = cells_data(
      columns = vars(num),
      rows = num > 100 & num < 10000)
  )
```

<img width="431" alt="top-border-missing" src="https://user-images.githubusercontent.com/5612024/63184076-90128800-c024-11e9-81b6-cd5e978390bb.png">

The solution to this shouldn't have anything to do with increased specificity when drawing border lines (these are already done as inline `style`s) but, likely, to change the drawing order of the row lines. Currently row lines are part of the `gt_row` CSS class:

```scss
  .gt_row {
    padding: $row_padding; /* row.padding */
    margin: 10px;
    border-bottom-style: solid;
    border-bottom-width: thin;
    border-bottom-color: #D3D3D3;
    vertical-align: middle;
    overflow-x: hidden;
  }
```

My thought is that we could substitute all `border-bottom-*` rules for `border-top-*` rules and  avoid the line-drawing conflict between row lines and border lines altogether.
