### ISSUE TITLE
Modify Travis CI build process to check more versions of R

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#59]
Currently, it just checks the present release. We should instead use (in `travis.yml`):

```
r:
  - oldrel
  - release
  - devel
```

or something more comprehensive like:

```
jobs:
  include:
  - r: release
  - r: devel
  - r: 3.4
  - r: 3.3
  - r: 3.2
```
