### ISSUE TITLE
Create a `.gt_table_center` CSS class and use it as a default option

### ISSUE THREAD

**Issue by rich-iannone** [rstudio/gt#60]
To allow setting a table to be centered in the content area, we could create a `.gt_table_center` CSS class and set that by default (perhaps with other options to left/right-align the table). It would contain these CSS rules: 

```
margin-left: auto;
margin-right: auto;
```

**Comment by andrewheiss** [comment]
Was about to open a new issue, but found this. Currently the only way I've found to left/right align HTML tables is to include this as a separate CSS file:

```css
.gt_table {
  margin-left: 0 !important;
  margin-right: 0 !important;
}
```

It works, but it'd be nice to have something in `tab_options()` that could allow for non-CSS overrides.
